Web/Controllers/HomeController.cs
using Entities.Users.UserDtos;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Services.LoginServices;
using Services.PageUrlsDataServices;
using Services.TokenServices;
using Services.UserDataServices;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ILoginService _loginService;
        private readonly ITokenService _tokenService;
        private readonly IPageUrlsDataService _pageUrlsDataService;
        private readonly IUserDataService _userService;

        public HomeController(ILogger<HomeController> logger, ILoginService loginService,
                ITokenService tokenService, IPageUrlsDataService pageUrlsDataService, IUserDataService userService)
        {
            _logger = logger;
            _loginService = loginService;
            _tokenService = tokenService;
            _pageUrlsDataService = pageUrlsDataService;
            _userService = userService;

        }
        public IActionResult create()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public async Task<IActionResult> updateAsync(Guid id)
        {
            var result = await _pageUrlsDataService.GetAsync(id);
            if (result != null)
                return View(result.Data.PageUrl);
            return BadRequest();
        }

        public async Task<IActionResult> deleteAsync(Guid id)
        {
            var result = await _pageUrlsDataService.GetAsync(id);
            if (result != null)
                return View(result.Data.PageUrl);
            return BadRequest();
        }
      
        public async Task<IActionResult> Login( string userName, string password)
        {
            var users = await _loginService.LoginAsync(userName, password);
            if (users != null)
            {

                var token = _tokenService.GetToken(users);
                var response = new
                {
                    Status = true,
                    Token = token,
                    Type = "Bearer",
                    UserId = users.Data.User.Id,
                    PageUrlList = users.Data.User.PageUrls
                };
               
               
                return RedirectToAction("Privacy", "Home", new { id = response.UserId });


            }
            else
                return BadRequest(string.Empty);

        }
       
        public async Task<IActionResult> LogOut()
        {
            Response.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetList()
        {
            var result = await _pageUrlsDataService.GetListAsync();
            if (result != null)
                return View(result);
            return BadRequest();
        }

        public async Task<IActionResult> PrivacyAsync(Guid id)
        {
            var result = await _pageUrlsDataService.GetUserIdAsync(id);

            return View(result.Data.PageUrls);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/PageUrlController.cs
using Entities.PageUrls.PageUrlsDtos;
using Microsoft.AspNetCore.Mvc;
using Services.PageUrlsDataServices;
using Services.UserDataServices;

namespace Web.Controllers
{
    public class PageUrlController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult create()
        {
            return View();
        }
        public IActionResult delete()
        {
            return View();
        }

        private readonly IPageUrlsDataService _pageUrlsDataService;


        public PageUrlController(IPageUrlsDataService pageUrlsDataService)
        {
            _pageUrlsDataService = pageUrlsDataService;
        }



        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetList()
        {
            var result = await _pageUrlsDataService.GetListAsync();
            if (result != null)
                return RedirectToAction("Privacy", "Home", result);
            return BadRequest();
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var result = await _pageUrlsDataService.GetAsync(id);
            if (result != null)
                return RedirectToAction("Privacy", "Home");
            return BadRequest();
        }

        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> GetByUserId(Guid id)
        {
            var result = await _pageUrlsDataService.GetUserIdAsync(id);
            if (result != null)
                return RedirectToAction("delete", "Home");
            return BadRequest();
        }
        public class tokk
        {
            public Guid tokakaka;
        }
        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> PageAddAsync(PageUrlsAddDtos pageUrlsAddDtos)
        {
           
            var result = await _pageUrlsDataService.AddAsync(pageUrlsAddDtos);
            if (result != null)
                return RedirectToAction("Privacy", "Home");
            return BadRequest();

        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> PageUpdateAsync(PageUrlsUpdateDtos pageUrlsUpdateDtos)
        {
            var result = await _pageUrlsDataService.UpdateAsync(pageUrlsUpdateDtos);
            if (result != null)
                return RedirectToAction("Privacy", "Home");
            return BadRequest();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> PageDelete(Guid id)
        {
            var result = await _pageUrlsDataService.DeleteAsync(id);
            if (result != null)
                return RedirectToAction("Privacy", "Home");
            return BadRequest();
        }
    }
}

Web/Views/Home/Index.cshtml
@model Entities.Users.User
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<body>

    @using (Html.BeginForm("Login", "Home",  FormMethod.Post))
 { 
      <div class="content">
        <!--Echo out errors here. See example-->
        <!--<p class=error>Error, wrong username or password used. Please, try again.-->
    
            <div class="mat-in d-flex justify-content-center">@Html.LabelFor( f => f.UserName)<br><br>
                <span class="bar"></span>
                   @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
            <div class="mat-in d-flex justify-content-center">@Html.LabelFor( f => f.Password)<br><br>
                 @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                <span class="bar"></span>
                 

            </div>
            <button type="submit" name="submit" id="login">Login</button>
       
   
    </div>
 }          
   
    <div class="bg-boxes">
        <svg width="300px" height="100%" id="col1">
            <rect width="150px" height="150px" x="75px" y="75px" class="bubble" id="bub1" />
        </svg>
        <svg width="200px" height="100%" id="col2">
            <rect width="100px" height="100px" x="50px" y="50px" class="bubble" id="bub2" />
        </svg>
        <svg width="260px" height="100%" id="col3">
            <rect width="130px" height="130px" x="65px" y="65px" class="bubble" id="bub3" />
        </svg>
        <svg width="160px" height="100%" id="col4">
            <rect width="80px" height="80px" x="40px" y="40px" class="bubble" id="bub4" />
        </svg>
        <svg width="240px" height="100%" id="col5">
            <rect width="120px" height="120px" x="60px" y="60px" class="bubble" id="bub5" />
        </svg>
        <!--Here is a triangle-->
        <svg width="200px" height="100%" id="col6">
            <polygon points="50,150 100,50 150,150" class="bubble" id="bub6" />
        </svg>
        <svg width="200px" height="100%" id="col7">
            <rect width="100px" height="100px" x="50px" y="50px" class="bubble" id="bub7" />
        </svg>
        <svg width="200px" height="100%" id="col8">
            <rect width="100px" height="100px" x="50px" y="50px" class="bubble" id="bub8" />
        </svg>
        <svg width="200px" height="100%" id="col9">
            <rect width="100px" height="100px" x="50px" y="50px" class="bubble" id="bub9" />
        </svg>
        <svg width="200px" height="100%" id="col10">
            <rect width="100px" height="100px" x="50px" y="50px" class="bubble" id="bub10" />
        </svg>
        <svg width="100px" height="100%" id="col11">
            <rect width="50px" height="50px" x="25px" y="25px" class="bubble" id="bub11" />
        </svg>
    </div>
    
</body>

Web/Views/Home/create.cshtml
@model Entities.PageUrls.PageUrlsDtos.PageUrlsAddDtos

 <nav class="navbar">
  <div class="container">

    <div class="navbar-header">
      <button class="navbar-toggler" data-toggle="open-navbar1">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a href="#">
        <h4>Awesome<span>logo</span></h4>
      </a>
    </div>

    <div class="navbar-menu" id="open-navbar1">
      <ul class="navbar-nav">  
        <li> @Html.ActionLink("Url Create","create", "Home" )</li>
        <li> @Html.ActionLink("Url List","Privacy", "Home" )</li>
        <li> @Html.ActionLink("User List","UserList", "User" )</li>
        <li> @Html.ActionLink("User Create","UserCreate", "User" )</li>
        <li>@Html.ActionLink("Sign Out", "Index" , "Home")</li>
      </ul>
    </div>
  </div>
</nav>
@using (Html.BeginForm("PageAdd", "PageUrl",  FormMethod.Post)) 
{
  
    <div class="form-horizontal text-center">
        <h4>URL Create</h4>
        <hr />
         @Html.HiddenFor(model => model.UserId)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group d-flex justify-content-center">
             <div class="col-md-2 ">
                <p>URL Name: </p>
            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.UrlName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlName, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group d-flex justify-content-center">
             <div class="col-md-2 ">
                <p>URL Address: </p>
            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.UrlAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group d-flex justify-content-center">
               <button type="submit" class="btn btn-labeled btn-success">
         <span class="btn-label"><i class="fa fa-check"></i></span>Success</button>
        </div>
    </div>
}

Web/Views/Home/delete.cshtml
@model Entities.PageUrls.PageUrl

 <nav class="navbar">
  <div class="container">

    <div class="navbar-header">
      <button class="navbar-toggler" data-toggle="open-navbar1">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a href="#">
        <h4>Awesome<span>logo</span></h4>
      </a>
    </div>

    <div class="navbar-menu" id="open-navbar1">
      <ul class="navbar-nav">  
        <li> @Html.ActionLink("Url Create","create", "Home" )</li>
        <li> @Html.ActionLink("Url List","Privacy", "Home" )</li>
        <li> @Html.ActionLink("User List","UserList", "User" )</li>
        <li> @Html.ActionLink("User Create","UserCreate", "User" )</li>
        <li>@Html.ActionLink("Sign Out", "Index" , "Home")</li>
      </ul>
    </div>
  </div>
</nav>


<div class="card text-center" >
  <div class="card-body">
    <h3>Are you sure you want to delete this?</h3>
   <hr />
    <dl class="dl-horizontal">
        <dt>
            URL Name:
        </dt>
         <dd>
            @Html.DisplayFor(model => model.UrlName)
        </dd>
         <dt>
            URL Address:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UrlAddress)
        </dd>
    </dl>
  
    @using (Html.BeginForm("PageDelete", "PageUrl",  FormMethod.Post)) {
    
         @Html.HiddenFor(model => model.Id)
       
                <button type="submit" class="btn btn-labeled btn-danger">
         <span class="btn-label"><i class="fa fa-trash"></i></span>Trash</button>
    }
  </div>
</div>


   

Web/Views/Home/update.cshtml
@model Entities.PageUrls.PageUrl

  <nav class="navbar">
  <div class="container">

    <div class="navbar-header">
      <button class="navbar-toggler" data-toggle="open-navbar1">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a href="#">
        <h4>Awesome<span>logo</span></h4>
      </a>
    </div>

    <div class="navbar-menu" id="open-navbar1">
      <ul class="navbar-nav">  
        <li> @Html.ActionLink("Url Create","create", "Home" )</li>
        <li> @Html.ActionLink("Url List","Privacy", "Home" )</li>
        <li> @Html.ActionLink("User List","UserList", "User" )</li>
        <li> @Html.ActionLink("User Create","UserCreate", "User" )</li>
        <li>@Html.ActionLink("Sign Out", "Index" , "Home")</li>
      </ul>
    </div>
  </div>
</nav>



@using (Html.BeginForm("PageUpdate", "PageUrl",  FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-center">
        <h3>Are you sure you want to update this?</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <br>
        <div class="form-group d-flex justify-content-center">
             <div class="col-md-2 ">
                <p>URL Name: </p>
            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.UrlName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlName, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group d-flex justify-content-center">
             <div class="col-md-2 ">
                <p>URL Address: </p>
            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.UrlAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group d-flex justify-content-center">
            <div class="col-md-offset-2 col-md-10">
               
                  <button type="submit" class="btn btn-labeled btn-success">
         <span class="btn-label"><i class="fa fa-check"></i></span>Success</button>
            </div>
        </div>
    </div>
}